---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.11
    executor:
      name: "samvera/ruby"
      ruby_version: << parameters.ruby_version >>
    environment:
      WAIT_FOR_JEKYLL: 10
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]
      - run:
          name: Install the NPM dependencies using Yarn
          command: |
            yarn install -D
      - run:
          name: Lint the formatting of source code files using Prettier
          command: |
            yarn run prettier --check .
      - persist_to_workspace:
          root: ~/
          paths:
            - project/*
            - project/**/*

workflows:
  version: 2
  ci:
    jobs:
      - bundle_and_test:
          name: ruby3-1
          ruby_version: 3.1.1

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - bundle_and_test:
          name: ruby3-1
          ruby_version: 3.1.1
