---
rubygems:
  gems:
    # [GitHub Repository]: [RubyGems Gem]
    active_fedora: active-fedora
    fcrepo-admin: fcrepo_admin
    questioning_authority: qa
repositories:
  invalid:
    # samvera
    - cla-bot
    - cla-bot-old
    - hyku
    - maintenance
    - samvera-circleci-orb
    - samvera.github.io
    # samvera-labs
    - ActiveTriples
    - starter-react-component-npm
    - stencil-test-components
    - sufia.io
    - samvera-connect
    - samvera-labs.github.io
    - samvera-persona
    - samvera-virtual-connect
    - samvera.org
    - samvera_docs
    - serverless-iiif
    - sessionizer
    - uri_selection_wg
    - ValkyrieAPI
    - repository_utils
    - power-steering
    - openseadragon-react-viewer
    - nurax-pg
    - node-iiif
    - nectar-iiif
    - browse-everything-components
    - browse-everything-redux-react
    - iiif-image-api
    - iiif-react-media-player
    - hyku-api
    - hyku.github.io
    - docker-fcrepo
    - fcrepo-charts
    - fcrepo3
    - fcrepo3-ldp
    - core-dependency-report
    - digital_collections_elixir_example
    - branch-renaming-wg
    - bloom-iiif
    - AdvancingHyku
    - ansible-sufia7-playbook
    - clover-iiif
    - houndstooth
    - image-downloader
    - allinson_flex
    - analytics_nurax
    - avalon-bundle
    - book_concerns
    - doi_registrar
    - hybox-ideas
    - hydra-admin-collections
    - hydra-shibboleth
    - hydra_controlled_vocabularies
    - hydra_documentation_wg
    - hydra_file_sets_wg
    - hydra_plugins_wg
    - hyrax-batch_ingest..
    - hyrax-google_analytics
    - hyrax-hirmeos
    - hyrax-json_fields
    - hyrax-orcid
    - hyrax-speed_test
    - karmabot
    - open_annotation_models
    - rdf-proxy_list
    - ruby-oai
    - samvera-external_storage
    - samvera-shibboleth
    - sipity
    - speedy_af
    - storage_proxy_api
    - valkyrie-cloud_search
    - valkyrie-derivatives
    - valkyrie-dynamodb
    - valkyrie-redis
    - valkyrie_pg_demo
    - hyrax-batch_ingest
